name: stop_watch_timer
description: Simple CountUp timer / CountDown timer. It easily create app of stopwatch.
version: 3.1.1
repository: https://github.com/hukusuke1007/stop_watch_timer
homepage: https://github.com/hukusuke1007/stop_watch_timer

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  rxdart: ^0.27.7

dev_dependencies:
  pedantic_mono: ^1.26.0
